# Generated by Django 4.2.17 on 2025-01-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_remove_user_login_key_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
